version: "3"

services:
  db:
    container_name: database_server
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=atlan_app
      - MYSQL_PASSWORD=atlan_pass
      - MYSQL_DATABASE=atlan
    ports:
      - 3306:3306
    restart: always
  server:
    container_name: backend_server
    environment:
      - WAIT_HOSTS=database_server:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=20
      - WAIT_HOST_CONNECT_TIMEOUT=30
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/server/src
#    command: nodemon -L src/server.js
    command: sh -c "/wait && npm run migrate && npm run dev"
    links:
      - db
    restart: always
    depends_on:
      - db
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
    depends_on:
      - server